version: '3'
services:

  letsencrypt:
    image: cybergatelabs/letsencrypt
    restart: unless-stopped
    container_name: letsencrypt
    hostname: letsencrypt
    ports:
      - 80:80
      - 443:443
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/letsencrypt/config:/config
    env_file: 
      - ./.letsencrypt.env
    networks:
      - signal-net
    
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - signal-net
  
  postgresql:
    image: postgresql:11
    container_name: postgresql
    hostname: postgresql
    restart: unless-stopped
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    env_file: 
      - ./.postgresql.env
    networks:
      - signal-net
 
  dbadmin:
    image: cybergatelabs/dbadmin
    container_name: dbadmin
    hostname: dbadmin
    restart: always
    #ports:
    #  - 8080:8080
    networks:
      - backend
 
  testhelper:
    image: registry.git.callpipe.com/finn/signald-test-infrastructure/testhelper:master
    restart: always
    build:
      context: .
      dockerfile: testhelper.Dockerfile
    environment:
      DB: "host=db user=signal dbname=signal password=password sslmode=disable"
    ports:
      - "127.0.0.1:8082:8082"
  signal:
    image: registry.git.callpipe.com/finn/signald-test-infrastructure/signal-server:2.02
    build:
      context: .
      dockerfile: signal-server.Dockerfile
    volumes:
      - "./signal-server.yaml:/etc/signal-server.yaml"
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
volumes:
  postgresql-data:

networks:
  signal-net:
    driver: bridge
      driver_opts:
        com.docker.network.bridge.name: br-signal
    ipam:
      driver: default
      config:
        - subnet: 172.16.240.0/24
