version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: signal
    expose:
      - 5432
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
  adminer:
    image: adminer
    restart: always
    ports:
     - "127.0.0.1:8083:8080"
  testhelper:
    image: registry.git.callpipe.com/finn/signald-test-infrastructure/testhelper:master
    restart: always
    build:
      context: .
      dockerfile: testhelper.Dockerfile
    environment:
      DB: "host=db user=signal dbname=signal password=password sslmode=disable"
    ports:
      - "127.0.0.1:8082:8082"
  signal:
    image: registry.git.callpipe.com/finn/signald-test-infrastructure/signal-server:2.02
    build:
      context: .
      dockerfile: signal-server.Dockerfile
    volumes:
      - "./signal-server.yaml:/etc/signal-server.yaml"
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
